# run command: python create_new_index.py elasticsearch_url
import os
import sys
os.system("curl -XPUT '" + str(sys.argv[1]) + "/supersonic'"
    + " -H \"Content-Type: application/json\" -d \"{"
      	+ "\\\"mappings\\\": {"
            + "\\\"doc\\\": {"
                + "\\\"properties\\\":{"
                    + "\\\"customer_pay_id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"account_number\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"receipts_date\\\" : {"
                        + "\\\"type\\\": \\\"date\\\","
                        + "\\\"format\\\": \\\"yyyy-MM-dd HH:mm:ss.SSSSSSS\\\""
                        + "},"
                    + "\\\"receipts_amount\\\" : {\\\"type\\\": \\\"long\\\"},"
                    + "\\\"shop_code\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"np_transaction_id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"ir_flg\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"transfer_name\\\" : {\\\"type\\\": \\\"text\\\"},"
                    + "\\\"bank_code\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"branch_code\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"tantocd\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"action_id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                    + "\\\"furikae_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"azukari_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"seikyugaku\\\" : {\\\"type\\\" : \\\"long\\\"},"
                    + "\\\"customer_name\\\" : {\\\"type\\\": \\\"text\\\"},"
                    + "\\\"sk_kaisyacd\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"sk_seqno\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"sk_gyono\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"nk_kaisyacd\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"nk_seqno\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"nk_gyono\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"nyukingaku\\\" : {\\\"type\\\" : \\\"long\\\"},"
                    + "\\\"nyukin_key\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"seikyu_key\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"otoiawasebango\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                    + "\\\"azukari_histories\\\": {"
                        + "\\\"type\\\":\\\"nested\\\","
                        + "\\\"properties\\\": {"
                            + "\\\"id\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"ir_flg\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"action_id\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"furikae_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                            + "\\\"azukari_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                            + "\\\"r_ymd\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"r_id\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"tantocd\\\": { \\\"type\\\": \\\"keyword\\\" },"
                            + "\\\"memo\\\": { \\\"type\\\": \\\"text\\\" }"
                            + "}"
                        + "}"
                    + "}"
              	+ "}"
            + "}"
        + "}"
    + "}\"")
