import os
os.system("curl -XPUT 'https://search-supersonic-mvgfqpixln7qd3ldpqpslpenra.ap-northeast-1.es.amazonaws.com/supersonic'"
    + " -H \"Content-Type: application/json\" -d \"{"
  	+ "\\\"mappings\\\": {"
        + "\\\"customer_pay\\\": {"
            + "\\\"properties\\\":{"
  	             + "\\\"id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"account_number\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                 + "\\\"receipts_date\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                 + "\\\"receipts_amount\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                 + "\\\"shop_code\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"np_transaction_id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"ir_flg\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"transfer_name\\\" : {\\\"type\\\": \\\"text\\\"},"
                 + "\\\"bank_code\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"tantocd\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"action_id\\\" : {\\\"type\\\" : \\\"keyword\\\"},"
                 + "\\\"furikae_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                 + "\\\"azukari_status_id\\\" : {\\\"type\\\": \\\"keyword\\\"},"
                 + "\\\"azukari_histories\\\": {"
                 + "\\\"type\\\":\\\"nested\\\","
                 + "\\\"properties\\\": {"
                    + "\\\"id\\\": { \\\"type\\\": \\\"keyword\\\" },"
                    + "\\\"memo\\\": { \\\"type\\\": \\\"text\\\" }"
                    + "}"
  				+ "}"
  			+ "}"
  		+ "}"
  	+ "}"
    + "}\"")
