# search customer_pay by azukari_history of memo
import os
memo = "thao"
os.system("curl -XPOST 'https://search-supersonic-mvgfqpixln7qd3ldpqpslpenra.ap-northeast-1.es.amazonaws.com/supersonic/_search'"
    + " -H \"Content-Type: application/json\" -d \"{"
    + "\\\"query\\\": {"
        + "\\\"bool\\\": {"
            + "\\\"must\\\": ["
                + "{"
                    + "\\\"nested\\\": {"
                        + "\\\"path\\\": \\\"azukari_histories\\\","
                        + "\\\"score_mode\\\": \\\"max\\\","
                        + "\\\"query\\\": {"
                            + "\\\"bool\\\": {"
                                + "\\\"must\\\": ["
                                    + "{"
                                        + "\\\"match\\\": {"
                                            + "\\\"azukari_histories.memo\\\": \\\"" + memo + "\\\""
                                        + "}"
                                    + "}"
                                + "]"
                            + "}"
                        + "}"
                    + "}"
                + "}"
            + "]"
        + "}"
    + "}"
    + "}\"")
