# update customer_pay
import os
memo = "dekiru2"
customer_pay_id = "52375223"
id = "1001"
os.system("curl -XPOST 'https://search-super-sonic-3rbymj6u6ymc5squcbhge3vdla.ap-northeast-1.es.amazonaws.com/supersonic/customer_pay/"
    + customer_pay_id + "/_update'"
    + " -H \"Content-Type: application/json\" -d \"{"
    + "\\\"script\\\":{"
        + "\\\"lang\\\":\\\"painless\\\","
        + "\\\"inline\\\":\\\"if (!ctx._source.containsKey(\\\\\\\"azukari_histories\\\\\\\")) {"
        + "ctx._source.azukari_histories = [];ctx._source.azukari_histories.add(params.child);} else {"
        + "int flag=0;for(int i=0;i<ctx._source.azukari_histories.size();i++){"
        + "if(ctx._source.azukari_histories[i].id==params.child.id){"
        + "ctx._source.azukari_histories[i]=params.child;flag++;}}if(flag==0){"
        + "ctx._source.azukari_histories.add(params.child);}}\\\","
            + "\\\"params\\\":{"
                + "\\\"child\\\":{"
                    + "\\\"id\\\":\\\"" + id + "\\\","
                    + "\\\"memo\\\": \\\"" + memo + "\\\""
                + "}"
            + "}"
    + "}"
    + "}\"")
